package VIEW;

import Model.Produto;
import DAO.ProdutoDAO;
import java.awt.Color;
import java.awt.LayoutManager;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

public class EstoqueProduto extends javax.swing.JFrame {

    public EstoqueProduto() {
        initComponents();
        this.getContentPane().setBackground(new Color(188,219,255));
        atualizarEstoque();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_cancelar = new javax.swing.JButton();
        B_add_produto = new javax.swing.JButton();
        tabbed_panel = new javax.swing.JTabbedPane();
        unidades_estoque = new javax.swing.JPanel();
        estoqueLabel = new javax.swing.JLabel();
        B_atualizar = new javax.swing.JButton();

        setTitle("Visualização de Estoque");

        B_cancelar.setText("Cancelar");
        B_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cancelarActionPerformed(evt);
            }
        });

        B_add_produto.setText(" Novo produto");
        B_add_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_add_produtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unidades_estoqueLayout = new javax.swing.GroupLayout(unidades_estoque);
        unidades_estoque.setLayout(unidades_estoqueLayout);
        unidades_estoqueLayout.setHorizontalGroup(
            unidades_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unidades_estoqueLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(estoqueLabel)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        unidades_estoqueLayout.setVerticalGroup(
            unidades_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unidades_estoqueLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(estoqueLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tabbed_panel.addTab("Unidades totais disponíveis no estoque", unidades_estoque);

        B_atualizar.setText("Atualizar");
        B_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(B_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(B_atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(B_add_produto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tabbed_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(tabbed_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_cancelar)
                    .addComponent(B_add_produto)
                    .addComponent(B_atualizar))
                .addGap(65, 65, 65))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_B_cancelarActionPerformed

    private void B_add_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_add_produtoActionPerformed
        CadastrarProduto objeto = new CadastrarProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_B_add_produtoActionPerformed

    private void B_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_atualizarActionPerformed
        this.setVisible(false);
        EstoqueProduto objeto = new EstoqueProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_B_atualizarActionPerformed

    // recupera o valor de totalEstoque em ProdutoDAO
    private void atualizarEstoque() {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        int totalEstoque = produtoDAO.somarEstoque();
        estoqueLabel.setText("Total de Unidades: " + totalEstoque);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_add_produto;
    private javax.swing.JButton B_atualizar;
    private javax.swing.JButton B_cancelar;
    private javax.swing.JLabel estoqueLabel;
    private javax.swing.JTabbedPane tabbed_panel;
    private javax.swing.JPanel unidades_estoque;
    // End of variables declaration//GEN-END:variables

}